server:
  port: 8080

spring:
  application:
    name: order-services
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orders
        format_sql: true

  flyway:
    enabled: true
    schemas: orders
    default-schema: orders
    create-schemas: true
    table: flyway_schema_history_orders

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

app:
  kafka:
    topics:
      orderCreated: orders.created.v1
      paymentProcessed: payments.processed.v1